Instagram/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('<int:user_id>/follow/', views.follow, name='follow'),
]

Instagram/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('posts.urls')),
    path('accounts/', include('accounts.urls')),
]

Instagram/conifg/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('instagram/', include('instagram.urls')),
]

Instagram/posts/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = "posts"

urlpatterns = [
    path('', views.index, name = 'index'),
    path('posts/', views.posts, name = 'posts'),
    path('<int:user_id>/posts/create/', views.create_post, name = 'create_post'),
    path('<int:user_id>/posts/<int:pk>/', views.read_post, name = 'read_post'),
    path('<int:user_id>/posts/<int:pk>/update/', views.update_post, name = 'update_post'),
    path('<int:user_id>/posts/<int:pk>/delete/', views.delete_post, name = 'delete_post'),
    path('<int:user_id>/posts/<int:pk>/comments/', views.read_comments, name = 'read_comments'),
    path('<int:user_id>/posts/<int:pk>/comments/create/', views.create_comment, name = 'create_comment'),
    path('<int:user_id>/posts/<int:post_id>/comments/<int:comment_id>/update/', views.update_comment, name = 'update_comment'),
    path('<int:user_id>/posts/<int:post_id>/comments/<int:comment_id>/delete/', views.delete_comment, name = 'delete_comment'),
    path('posts/search/', views.search_post, name = 'search_post'),
    path('<int:user_id>/posts/<int:post_id>/like/', views.like, name = 'like'),
    # path('posts/like_list/', views.like_list, name = 'like_list'),
    path('posts/my_page/', views.my_page, name = 'my_page'),
]

Instagram/posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length = 100)
    content = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    image = models.ImageField(null=True, blank=True, upload_to="image")
    likes = models.ManyToManyField(settings.AUTH_USER_MODEL, blank=True, related_name = 'like_users')



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)   #, related_name='comments'
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete = models.CASCADE)
    message = models.TextField()

# posts.Post.author: (fields.E304) Reverse accessor for 'Post.author' clashes with reverse accessor for 'Post.likes'.
#         HINT: Add or change a related_name argument to the definition for 'Post.author' or 'Post.likes'.
# posts.Post.likes: (fields.E304) Reverse accessor for 'Post.likes' clashes with reverse accessor for 'Post.author'.
#         HINT: Add or change a related_name argument to the definition for 'Post.likes' or 'Post.author'.

Instagram/posts/forms.py
from django import forms
from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['image', 'title', 'content']
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

Instagram/posts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.db.models import Q
from django.contrib.auth import get_user_model

# Create your views here.

# 인덱스 페이지
def index(request):
    user = request.user

    if user.is_authenticated:        
        return redirect('posts:posts')
    else:
        return redirect('accounts:login')


# 전체 게시글(내 게시글, 팔로우 게시글) list 페이지 (Read)
def posts(request):
    posts = Post.objects.all()
    
    context = { 'posts' : posts }
    return render(request, 'posts/list.html', context)

    # followings = request.user.followings.values_list("-id", flat=True)
    # followings.append(request.user.id)
    
    # posts = Post.objects.filter(user__in=followings).order_by("-id")
    # context = {'posts', posts}

    # return render(request, 'posts/list.html', context)


# 게시글 작성 (Create)
def create_post(request, user_id):

    user = request.user
    # print('request', request, dir(request))
    if request.method == "POST":
        form = PostForm(request.POST)
            
        if form.is_valid():
            post = form.save(commit=False)
            post.author = user
            post.save()
            return redirect('posts:posts')

    form = PostForm()
    context = { 'form' : form }
    return render(request, 'posts/create_post.html', context)
    
        
# 게시글 읽기 (Read)
def read_post(request, pk, user_id):
    post = get_object_or_404(Post, pk=pk)
    comments = post.comment_set.all()
    people = get_object_or_404(get_user_model(), id=user_id)

    context = { 'post' : post, 'comments' : comments, 'people' : people }
    return render(request, 'posts/post.html', context)

# 게시글 수정 (Update)
def update_post(request, pk, user_id):
    post = get_object_or_404(Post, pk=pk)

    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            form.save()
            return redirect('posts:read_post', pk=pk, id=user_id)
    
    form = PostForm(instance=post)
    context = {'form' : form}
    return render(request, 'posts/update_post.html', context)

# 게시글 삭제 (Delete)
def delete_post(request, pk, user_id):
    post = Post.objects.get(pk=pk)
    post.delete()
    return redirect('posts:read_post', pk=pk, id=user_id)

# 댓글 작성 (Create)
def create_comment(request, pk, user_id):
    
    if request.method == "POST":
        post = get_object_or_404(Post, pk=pk)
        message = request.POST.get('message')

        if not message:
            return HttpResponse('댓글 내용을 입력하세요', status=400)
        
        Comment.objects.create( post=post, author=request.user, message=message)
        return redirect('posts:read_post', id=user_id, pk=pk)
    
    form = CommentForm()
    context = { 'form' : form }
    return render(request, 'posts/create_comment.html', context)

# 댓글 읽기 (Read)
def read_comments(request, pk, user_id):
    post = get_object_or_404(Post, pk=pk)
    comments = post.comment_set.all()
    
    context = { 'post' : post, 'comments' : comments }
    return render(request, 'posts/read_comments.html', context)

# 댓글 수정 (Update)
def update_comment(request, post_id, comment_id, user_id):

    comment = get_object_or_404(Comment, pk=comment_id)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)

        if form.is_valid():
            comment.save()
            return redirect('posts:read_post', pk=post_id, id=user_id)
    
    form = CommentForm(instance=comment)
    context = { 'form' : form }
    return render(request, 'posts/update_comment.html', context)

# 댓글 삭제 (Delete)
def delete_comment(request, post_id, comment_id, user_id):

    comment = Comment.objects.get(pk=comment_id)
    comment.delete()
    
    return redirect('posts:read_post', pk=post_id, id=user_id)

# 검색 기능(검색이 이뤄지지 않았을 때는, 모든 게시물을 보여준다.)
def search_post(request):

    posts = Post.objects.all()
    keyword = ""

    if request.method == "POST":
        keyword = request.POST.get('keyword',"")  
        
        if keyword:
            posts = Post.objects.filter(Q(title__icontains=keyword) | Q(content__icontains=keyword) | Q(author__username__icontains=keyword)).order_by("-id")
        
    context = {'posts':posts, 'keyword':keyword}
    return render(request, 'posts/search_post.html', context)

# 좋아요 기능(좋아요 수 나타내기 용도)
def like(request, post_id, user_id):
    post = get_object_or_404(Post, pk = post_id)

    if post.likes.filter(username=request.user.username).exists():
        post.likes.remove(request.user)
    else:
        post.likes.add(request.user)
    
    post.save()
    return redirect('posts:read_post', post_id, user_id)

# 좋아요 리스트(좋아요 누른 개시물 보기)
# def like_list(request, user_id):
#     posts = Post.objects.all()

#     if request.user.is_authenticated:
#         posts = Post.likes.all(username=request.user.username)
#         context = {'posts' : posts}
#         return render(request, 'posts/like_list.html', context )
#     else:
#         context = {'post' : posts}
#         return render(request, 'posts/like_list.html', context )


# 나의 게시물만 모아둔 페이지
def my_page(request):
    user = request.user
    posts = Post.objects.filter(author__username=user).order_by("-id")
    
    context = {'posts': posts}
    return render(request, 'posts/my_page.html', context)

Instagram/templates/posts/create_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>create_comment</title>
</head>
<body>
    {{ comment.author }}<br>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_p }}
        </table>

        <input type="submit" value="댓글 등록">
    </form>
</body>
</html>

Instagram/templates/posts/create_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시물 작성</title>
</head>
<body>
    <h1>글 작성하기</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ post.as_p }}
        <input type="submit" value="글 작성하기">
    </form>
</body>
</html>

Instagram/templates/posts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Instagram</title>
</head>
<body>
    <h1>인덱스 페이지 입니다. 로그인 판별 후 알맞는 페이지로 넘어갑니다.</h1>
    
</body>
</html>

Instagram/templates/posts/like.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>likes</title>
</head>
<body>
    <form action="{% url 'posts:like' post.id %}" method="get">
        <input type="hidden" name='like' value="{{user}}">
        <button type="submit">좋아요</button>
    </form>
</body>
</html>

Instagram/templates/posts/like_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>like_list</title>
</head>
<body>
    좋아요 목록
    {% for post in posts %}
        {{post.author}}<br>
        {{post.image}}<br>
        {{post.title}}<br>
        {{post.content}}<br>
    <hr>
    {% endfor %}
</body>
</html>

Instagram/templates/posts/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">
    <title>Instagram</title>
</head>
<body>
    <div>
        <h1>Instagram</h1>

        <a href = "{% url 'accounts:logout' %}">로그아웃</a>
        <br>


        {% for post in posts %}
            {{post.author}}<br>
            {{post.image}}<br>
            {{post.title}}<br>
            {{post.content}}<br>
            <form action="{% url 'posts:like' post.id user.id %}" method="get">
              <input type="hidden" name='like' value="{{user}}">
              <button type="submit">좋아요</button>
            </form>
            <br>
            <a href="{% url 'posts:read_comments' user.pk post.pk %}">댓글</a>
            <hr>
        {% endfor %}
    </div>

    <div style = "width: 10px; height: 45px">

    </div>

    <div>
        
      <nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-bottom font-white">
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
              <ul class="navbar-nav mr-auto">
                
                <li class="nav-item">
                  <a class="fas fa-home" href ="/posts/" style="color: white"></a>
                  </li>
                  <li class="nav-item">
                    <a class="fas fa-search" href="/posts/search/" style="color: white"></a>
                  </li>
                <li class="nav-item">
                  <a class="nav-link" href="/posts/" style="color: white">좋아요</a>
                </li>
                <li class="nav-item">
                  <a class="fas fa-user" href="/posts/my_page/" style="color: white"></a>
                  </li>
               
              </ul>
        </nav>

</body>
</html>

Instagram/templates/posts/my_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">
    <title>Mylist</title>
</head>
<body>
    {% for post in posts %}
        <a href = "/{{user.id}}/posts/{{post.pk}}/">{{ post.author }}</a><br>
        <!-- {{post.author}}<br> -->
        {{post.image}}<br>
        {{post.title}}<br>
        {{post.content}}<br>
        <hr>
    {% endfor %}

    <div style = "width: 10px; height: 45px">
    </div>
    
    <div>
        
        <nav class="navbar navbar-expand-lg navbar-light bg-dark fixed-bottom font-white">
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                  
                  <li class="nav-item">
                    <a class="fas fa-home" href ="/posts/" style="color: white"></a>
                    </li>
                    <li class="nav-item">
                        <a class="fas fa-search" href="/posts/search/" style="color: white"></a>
                    </li>
                  <li class="nav-item">
                    <a class="nav-link" href="/posts/" style="color: white">좋아요</a>
                  </li>
                  <li class="nav-item">
                    <a class="fas fa-user" href="/posts/my_page/" style="color: white"></a>
                    </li>
                 
                </ul>
          </nav>

</body>
</html>

Instagram/templates/posts/post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>post</title>
</head>
<body>
    {{ post.author }}
    <!-- 팔로우/언팔로우 버튼 -->
    {{ people.followers.all }}
    {% if user != people %}
        {% if user in people.followers.all %}
            <a href="{% url 'accounts:follow' people.id %}">UnFollow</a>
        {% else %}
            <a href="{% url 'accounts:follow' people.id %}">Follow</a>
        {% endif %}
    {% endif %}
    <br>
    {{ post.image }}<br>
    {{ post.title }}<br>
    {{ post.content }}<br>

    <h4>comments</h4>
    <a href="{% url 'posts:create_comment' user.pk post.pk %}">댓글 작성</a>
    <ul>
        
        {% for comment in comments %}
             
            <li>
                <h4>{{ comment.author }}</h4>
                {{ comment.message }}
            </li>
            <a href="{% url 'posts:update_comment' user.pk post.pk comment.pk %}">댓글 수정</a>
            <a href="{% url 'posts:delete_comment' user.pk post.pk comment.pk %}">댓글 삭제</a>
        {% endfor %}
    </ul>
</body>
</html>

Instagram/templates/posts/read_comments.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>comments</title>
</head>
<body>
    <ul>
        {% for comment in comments %}
             
            <li>
                <h4>by {{ comment.author }}</h4>
                {{ comment.message }}

                <a href="{% url 'posts:update_comment' user.pk post.pk comment.pk %}">댓글 수정</a>
                <a href="{% url 'posts:delete_comment' user.pk post.pk comment.pk %}">댓글 삭제</a>
            </li>
        {% endfor %}
    </ul>

    <a href="{% url 'posts:create_comment' user.pk post.pk %}">댓글 작성</a>

</body>
</html>

Instagram/templates/posts/search_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>search</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        <button type="submit">Search</button>
        <input type="search" placeholder="검색" name="keyword" value="{{keyword}}">    
    </form>
    <br>
    {% for post in posts %}
        {{post.author}}<br>
        {{post.image}}<br>
        {{post.title}}<br>
        {{post.content}}<br>
        <hr>
    {% endfor %}
</body>
</html>

Instagram/templates/posts/update_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>update_comment</title>
</head>
<body>
    <h1>댓글 수정하기</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="댓글 수정하기">
    </form>
</body>
</html>

Instagram/templates/posts/update_post.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>update_post</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="글 수정하기">
    </form>

</body>
</html>