idco/IDCO/urls.py
from django.urls import path
from IDCO import views

app_name = "IDCO"

urlpatterns = [
    path('', views.list, name="list"),
    path('create/', views.create, name="create"),
    path('update/<int:pk>/', views.update, name="update"),
]

idco/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('templates/', include('IDCO.urls')),
]

idco/IDCO/models.py
from django.db import models


# Create your models here.
class Board(models.Model):

    title = models.CharField(max_length=100)
    content = models.TextField()

idco/IDCO/forms.py
from django import forms
from .models import Board       # 그 전에 없던 Board 를 import 해와야 한다.

class BoardForm(forms.ModelForm):           # ModelForm 과 Form 이 있는데, Form 은 너무 노가다이다.
    class Meta:
        model = Board
        fields = ['title', 'content'] # '__all__'               #Board 중에 사용할 것을 고른다.

idco/IDCO/views.py
from django.shortcuts import render, get_object_or_404
from IDCO.models import Board
from .forms import BoardForm

# Create your views here.
def list(request):
    # print('Board.objects', Board.objects, type(Board.objects))/채ㅜ'o
    # print('Board.objects.all', Board.objects.all, type(Board.objects.all))
    shurdang = Board.objects.all()
    # for i in shurdang:
    #     if '제목' in i.title:
    #         print(i.title)        
        
    # print('shurdang', shurdang, type(shurdang))
    context = { 'youtube': shurdang } 
    return render(request, 'index/list.html', context)

def create(request):
    
    if request.method == "POST":
        # print('request.POST', request.POST, type(request.POST))
        # board_t = request.POST.get('title')
        # board_c = request.POST.get('content')
        # print('board_t', board_t, type(board_t))
        # print('board_c', board_c, type(board_c))
        # form = Board.objects.create(title=board_t, content=board_c)
        # print('form', form, type(form))
        # return render(request, 'index/success.html')
        # print('if request.method == "POST"', request.method, type(request.method))    # HTML 메서드가 Post 일 경우, 각 매서드와 그 타입을 출력하여 확인한다,
        print('request.POST', request.POST, type(request.POST))
        form = BoardForm(request.POST)
        print('form', form, type(form))
        # print(form, 'form', type(form))       #   form 은 BoardForm(request.POST) 이다.
        if form.is_valid():
            print(form, type(form))
            form.save()
            print(form, type(form))                         #   
            return render(request, 'index/success.html')
        

    else:
    # print('else:', request.method, type(request.method))  # HTML 메서드가 Get 일 경우, 각 매서드와 타입을 출력하여 확인한다.
        youtube = BoardForm()
        # print('youtube', dir(youtube))

    context = { 'shurdang': youtube }
    return render(request, 'index/create.html', context)

def update(request, pk):
    board = get_object_or_404(Board, pk=pk)
    # print('board', board, type(board))
    # print('board.title', board.title, type(board.title))
    # print('board.content', board.content, type(board.content))
    board_test = Board.objects.get(pk=pk)
    print('board_test', board_test, type(board_test), dir(board_test))

    if request.method == "POST":
        form = BoardForm(request.POST, instance=board)
        # print('form', form, type(form))
        if form.is_valid():
            form.save()
            return render(request, 'index/success.html')

    else:
        form = BoardForm(instance=board)
        # print('form', form, type(form))

    context = { 'form': form }
    return render(request, 'index/update.html', context)

idco/templates/index/create.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시판 글 작성하기</title>
</head>
<body>
    <h1>글 작성하기</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ shurdang.as_p }}
        <input type="submit" value="글 작성하기">
    </form>
</body>
</html>

idco/templates/index/list.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>복습</title>
</head>
<body>
    <h1>게시판 글 목록</h1>
    <a href="/templates/create/"><button>글 작성하러 가기</button></a>
    {% for a in youtube %}
        <hr>
        id : {{ a.id }}<br>
        제목 : {{ a.title }}<br>
        내용 : {{ a.content }}<br>
        <a href="{% url 'IDCO:update' a.id %}"><button>글 수정하기</button></a>
    {% endfor  %}
    <hr>
</body>
</html>

idco/templates/index/success.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>글 작성 완료</title>
</head>
<body>
    <h1>성공!</h1>
    <a href="/templates/"><button>글 목록으로 돌아가기</button></a>
</body>
</html>

idco/templates/index/update.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시판 글 수정하기</title>
</head>
<body>
    <h1>글 수정하기</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="글 수정하기">
    </form>
</body>
</html>