CommentBoard/Boards/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = "Boards"

urlpatterns = [
    path('', views.boards, name = 'boards'),
    path('create/', views.create_board, name = 'board'),
    path('<int:pk>/update/', views.update_board, name = "update"),
    path('<int:pk>/delete/', views.delete_board, name = "delete"),
    path('<int:pk>/', views.page, name = "page"),
    path('<int:pk>/comment/create/', views.create_comment, name = "comment"),
    path('<int:board_id>/comments/<int:comment_id>/delete/', views.delete_comment, name='delete_comment'),
    path('<int:board_id>/comments/<int:comment_id>/update/', views.update_comment, name='update_comment'),
]

CommentBoard/accounts/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

app_name = "accounts"

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),    
]

CommentBoard/config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('boards/', include('Boards.urls')),
    path('accounts/', include('accounts.urls')),
]

CommentBoard/Boards/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Board(models.Model):

    title = models.CharField(max_length = 100)
    content = models.TextField()
    author = models.ForeignKey(User, on_delete = models.CASCADE)
    views = models.IntegerField(default = 0)
    image = models.ImageField(null=True, blank=True, upload_to="image")

class Comment(models.Model):

    # board = models.ForeignKey(Board)
    post = models.ForeignKey(Board, on_delete=models.CASCADE)   #, related_name='comments'
    # author = models.CharField(max_length = 10)
    message = models.TextField()

CommentBoard/Boards/forms.py
from django import forms
from .models import Board, Comment


class BoardForm(forms.ModelForm):
    class Meta:
        model = Board
        fields = ['title', 'content', 'image',]
    
class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['message']

CommentBoard/accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    class Meta:
        model = Userfields = ['username', 'password']

CommentBoard/Boards/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Board, Comment
from .forms import BoardForm, CommentForm
from django.db.models import Q
from django.contrib.auth.models import User


# Create your views here.

#Boards 는 게시글들의 목록을 볼 수 있는 게시판
def boards(request):

    boards = Board.objects.all()
    keyword = ""

    if request.method == "POST":
        keyword = request.POST.get('keyword',"")
        menu = request.POST.get('menu',"")
     
        if menu == "search_boards_by_all":
            if keyword:
                boards = Board.objects.filter(Q(title__icontains=keyword) | Q(content__icontains=keyword) | Q(author__username__icontains=keyword)).order_by("-id")
        elif menu == "search_boards_by_title":
            if keyword:
                boards = Board.objects.filter(title__icontains=keyword).order_by("-id")
        
        elif menu == "search_boards_by_content":
            if keyword:
                boards = Board.objects.filter(content__icontains=keyword).order_by("-id")
        else:
            if keyword:
                boards = Board.objects.filter(author__username__icontains=keyword).order_by("-id")
    for board in boards:
        print(board.image)
    context = {'boards':boards, 'keyword':keyword}
    return render(request, 'index/Boards.html', context)


#Create_post 는 게시글 한 개 쓰기
def create_board(request):

    if request.method == "POST":
        form = BoardForm(request.POST, request.FILES)

        if form.is_valid():
            board = form.save(commit = False)
            board.author = User.objects.get(username = request.user.get_username())
            board = form.save()
            return render(request, 'index/success.html')
   
    board = BoardForm()
    context = { 'board' : board } 
    return render(request, 'index/Board.html', context)


def update_board(request, pk):

    board = get_object_or_404(Board, pk=pk)

    if request.method == "POST":
        form = BoardForm(request.POST, instance=board)

        if form.is_valid():
            form.save()
            return render(request, 'index/success.html')
        
    board = BoardForm(instance=board)
    context = {'board':board}
    return render(request, 'index/update.html', context)

def delete_board(request, pk):

    board = Board.objects.get(pk=pk)

    board.delete()
    return render(request, 'index/success.html')

def page(request, pk):

    board = get_object_or_404(Board, pk=pk)
    comments = board.comment_set.all()

    board.views += 1
    board.save()

    context = {'board' : board, 'comments' : comments } 
    return render(request, 'index/page.html', context)

def create_comment(request, pk):

    board = get_object_or_404(Board, pk=pk)
    
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = board
            comment.save()
            return redirect('Boards:page', pk=board.pk)
    else:
        form = CommentForm()
    context = { 'form' : form }
    return render(request, 'index/comment.html', context)        


def delete_comment(request, board_id, comment_id):

    comment = Comment.objects.get(pk=comment_id)
    comment.delete()
    
    return redirect('Boards:page', board_id)

def update_comment(request, board_id, comment_id):

    board = board_id
    pk = comment_id
    comment = get_object_or_404(Comment, pk=pk)

    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)

        if form.is_valid():
            comment.save()
            return redirect('Boards:page', pk=board)
    else:
        form = CommentForm(instance=comment)
    context = { 'form' : form }
    return render(request, 'index/update_comment.html', context)

CommentBoard/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.
def signup(request):
    
    if request.method == "POST":
        if request.POST["password1"] == request.POST["password2"]:      #password1,2 가 같다면,
            User.objects.create_user(username=request.POST["username"],password=request.POST["password1"])   #입력한 username 과 password 로 user 를 생성한다.
            return redirect('accounts:login')
        else:
            return render(request, 'accounts/signup_pwError.html')

    return render(request, 'accounts/signup.html')

def login(request):

    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        user = auth.authenticate(request, username=username, password=password) #사용자한테 입력받은 username 과 password 를 user 에 저장한다.

        if user is not None:    # 그 user 가 있는지 없는지 판별
            auth.login(request, user)
            return redirect('Boards:boards')
        else:
            return render(request, 'accounts/login_error.html')
    else:
        return render(request,'accounts/login.html')


def logout(request):
    auth.logout(request)
    return redirect('Boards:boards')

CommentBoard/templates/accounts/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <div>
        <h2>login</h2>

        <form action="{% url 'accounts:login' %}" method="POST">
            {% csrf_token %}
            Username:
            <br>
            <input name="username" type="text">
            <br>
            Password:
            <br>
            <input name="password" type="password">
            <br><br>
            <input type="submit" value="login">
        </form>
    </div>
</body>
</html>

CommentBoard/templates/accounts/login_error.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>존재하지 않는 아이디 혹은 패스워드 입니다.</h2>
    <a href="{% url 'accounts:login' %}"><button>돌아가기</button></a>
</body>
</html>

CommentBoard/templates/accounts/signup.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>sign up</title>
</head>
<body>
    <div>
        <h2>sign up!</h2>

        <form action="{%url 'accounts:signup'%}" method="POST">
            {% csrf_token %}
            Username:
            <input name="username" type="text">
            <br>
            Password:
            <input name="password1" type="password">
            <br>
            Confrim Password:
            <input name="password2" type="password">
            <br><br>
            <input type="submit" value="sign up">            
        </form>
    </div>

    
</body>
</html>

CommentBoard/templates/accounts/signup_pwError.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>cofirm error</title>
</head>
<body>
    <h2>패스워드가 일지하지 않습니다.</h2>
    <a href="{% url 'accounts:signup' %}"><button>돌아가기</button></a>
    
</body>
</html>

CommentBoard/templates/index/Board.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>게시판 글 작성하기</title>
</head>
<body>
    <h1>글 작성하기</h1>
    <form action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ board.as_p }}
        
        <input type="submit" value="글 작성하기">
    </form>

</body>
</html>

CommentBoard/templates/index/Boards.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Board list</title>
</head>
<body>
    <div style = "background-color: rgb(73, 73, 73);">
        <h1 style = "color : white">게시판 글 목록</h1>
        
        <a href="/boards/create/" style="position:relative; top: 50px; left: 900px; color: #ffffff;
        background: #3379FE; padding: 0.3em 0.5em; margin-right: 0.1em; text-decoration:none">글 작성하러 가기</a>
        
        <!-- 검색창 -->
        <!-- <form action="" method="POST">
            {% csrf_token %}
            <input type="search" placeholder="Search" name="keyWord" value="{{keyWord}}">
            <button type="submit">Search</button>
        </form> -->
        <form action="" method="POST">
            {% csrf_token %}
            <input type="search" placeholder="Search" name="keyword" value="{{keyword}}">
            <select name="menu" >
              <option value="search_boards_by_all">통합검색</option>
              <option value="search_boards_by_title">제목검색</option>
              <option value="search_boards_by_content">내용검색</option>
              <option value="search_boards_by_user">아이디 검색</option>
            </select>
            <button type="submit">Search</button>
          </form>



    </div>

    <div style = "height: 25px;">
        <ul>
            <li style = "list-style: none; float: left; margin-left: 20px;">번호</li>
            <li style = "list-style: none; float: left; margin-left: 50px;">제목</li><br>
        </ul>
        {% if user.is_authenticated %}
        <a href="{% url 'accounts:logout' %}" style = "position: relative; top: -40px; left: 1050px; text-decoration:none; font-size: 0.8rem">로그아웃</a>
           
        {% else %}
        <ul>
            <li style = "list-style: none; position: relative; top: -50px; left: 1000px"><a href="{% url 'accounts:signup' %}" style = "text-decoration:none; font-size: 0.8rem">회원가입</a></li>
            <li style = "list-style: none; position: relative; top: -50px; left: 1000px"><a href="{% url 'accounts:login' %}" style = "text-decoration:none; font-size: 0.8rem">로그인</a></li>
        </ul>
    
        {% endif %}
    </div>

    <div>
        <hr>
        {% for board in boards %}
            <div style = "height: 40px;">
                <li style = "list-style: none; float: left; margin-left: 70px;">
                    {{ board.id }}
                </li>
                <li style = "list-style: none; float: left; margin-left: 60px;">
                    <a href = "/boards/{{board.pk}}/">{{ board.title }}</a>
                    <small><span>&nbsp&nbsp({{ board.author }}님의 글) 조회수 : {{ board.views }}</span></small>
                </li>
            </div>
            <div style = "position: relative; top: -45px; left: 900px;">
                <small><a href="{% url 'Boards:update' board.id %}" style = "text-decoration:none">글 수정하기</a></small><br>
                <small><a href="{% url 'Boards:delete' board.id %}" style = "text-decoration:none">글 삭제하기</a></small>
            </div>
        {% endfor %}
    </div>
</body>
</html>
<style>

</style>

CommentBoard/templates/index/comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <form action="" method="POST">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>

        <input type="submit" value="댓글 등록">
    </form>


</body>
</html>

CommentBoard/templates/index/page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>글 작성하기</title>
</head>
<body>
    <h1>글</h1>
    <small?><a href="/boards/"><button>글 목록으로 돌아가기</button></a></small><br>
    <br>
    <br>
        
        <small>{{ board.author }}님의 글</small><br><br>
        제목: {{ board.title }}<br>
        내용: {{ board.content }}<br>


    <h3>Comments</h3> 

    <a href = "{% url 'Boards:comment' pk=board.pk %}" board.pk>댓글 쓰기</a><br>
    
    <ul>
        
        {% for comment in comments %}
             
            <li>
                <h4>by {{ comment.author }}</h4>
                {{ comment.message }}
                <a href="{% url 'Boards:update_comment' board.pk comment.pk %}">댓글 수정</a>
                <a href="{% url 'Boards:delete_comment' board.pk comment.pk %}">댓글 삭제</a>
            </li>
        {% endfor %}
    </ul>
        
</body>
</html>

CommentBoard/templates/index/success.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>글 작성 완료</title>
</head>
<body>
    <h1>성공!</h1>
    <a href="/boards/"><button>글 목록으로 돌아가기</button></a>
    
</body>
</html>

CommentBoard/templates/index/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>글 수정하기</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ board.as_p }}
        <input type="submit" value="글 수정하기">
    </form>
    
</body>
</html>

CommentBoard/templates/index/update_comment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>댓글 수정하기</h1>
    <form action="" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="댓글 수정하기">
    </form>
    
</body>
</html>